name: Fetch RSS to Firestore

on:
  schedule:
    - cron: "0 23,4,9,14 * * *" # 6h,11h,16h,21h Việt Nam (UTC+7)
  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run RSS Job
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        run: node src/index.js
